---
:global:
  :linux1_username: root
  :linux1_domain: curso1819
:cases:
- :tt_members: jorge suarez
  :linux1_ip: "172.18.24.41"
  :linux1_password: VALUE
  :firstname: jorge
  :lastname1: suarez
  :number: "24"
