---
:global:
  :host1_username: root
  :host1_password: profesor
:cases:
- :tt_members: w10pro
  :host1_ip: 192.168.1.112
  :host1_hostname: sith.starwars
  :host1_username: idp
  :host1_password: idp
  :username: Administrador
- :tt_members: darth-maul
  :tt_skip: false
  :host1_ip: 192.168.1.200
  :host1_hostname: sith.starwars
  :username: dmaul
- :tt_members: r2d2
  :tt_skip: false
  :host1_ip: 192.168.1.201
  :host1_hostname: robot.starwars
  :username: true
- :tt_members: obiwan kenobi
  :tt_skip: true
  :host1_ip: 192.168.1.202
  :host1_hostname: jedi.starwars
  :username: obiwan
