---
:global:
  :host1_username: root
:cases:
- :tt_members: fran
  :host1_ip: 0.tcp.eu.ngrok.io
  :host1_port: 14879
  :host1_username: alumno
  :host1_password: onmula
  :host1_hostname: IDP
  :host2_ip: 192.168.1.1
  :host2_username: idp
  :host2_password: idp
  :host2_hostname: DESKTOP-57UFI2B
  :host2_ostype: windows
  :host2_route: host1
